insert into public.products
  (type, name, slug, category, price, old_price, rating, reviews, badge, images,
   care_level, colors, light, watering, pet_friendly, description)
values
  ('plant', 'Anthurium Flower', 'anthurium-flower', 'Flowering', 34, 40, 5, 48, 'SALE', array['plants/anthurium.webp', 'plants/peperomia.webp', 'plants/birds-nest-fern.webp'], 'Moderate', array['#292929', '#e9b86d', '#eee9dc', '#bc6831'], 'Bright indirect light', 'Water when the top inch of soil is dry', false, 'A striking flowering houseplant with glossy green leaves and vivid red blooms.'),
  ('plant', 'Peperomia Ginny', 'peperomia-ginny', 'Foliage', 25, null, 5, 36, 'NEW', array['plants/peperomia.webp'], 'Easy', array['#292929', '#e9b86d', '#eee9dc', '#bc6831'], 'Medium to bright indirect light', 'Let the soil partially dry between waterings', true, 'A compact variegated peperomia with attractive green, cream and pink-edged leaves.'),
  ('plant', 'Bird''s Nest Fern', 'birds-nest-fern', 'Foliage', 45, null, 5, 29, null, array['plants/birds-nest-fern.webp'], 'Moderate', array['#292929', '#e9b86d', '#eee9dc'], 'Medium to bright indirect light', 'Keep the soil lightly and consistently moist', true, 'A lush tropical fern with broad, gently rippled fronds growing from a central rosette.'),
  ('plant', 'Monstera Deliciosa', 'monstera-deliciosa', 'Foliage', 55, null, 4, 61, 'BESTSELLER', array['plants/monstera.webp'], 'Easy', array['#292929', '#e9b86d', '#eee9dc'], 'Bright indirect light', 'Water when the top 2 inches of soil are dry', false, 'A classic tropical houseplant recognized by its large, naturally split leaves.'),
  ('plant', 'Pink Calathea', 'pink-calathea', 'Flowering', 42, null, 5, 34, 'NEW', array['plants/pink-calathea.webp'], 'Moderate', array['#292929', '#e9b86d', '#eee9dc'], 'Bright filtered light', 'Keep soil evenly moist without waterlogging', true, 'A colorful prayer-plant style houseplant with pink, green and cream foliage.'),
  ('plant', 'Peace Lily', 'peace-lily', 'Flowering', 38, null, 4, 52, null, array['plants/peace-lily.webp'], 'Easy', array['#292929', '#e9b86d', '#eee9dc'], 'Medium to bright indirect light', 'Water when the surface begins to dry', false, 'An elegant flowering plant with glossy foliage and clean white blooms.'),
  ('plant', 'Snake Plant', 'snake-plant', 'Succulents & Cacti', 29, null, 5, 74, null, array['plants/snake-plant.webp'], 'Easy', array['#292929', '#e9b86d', '#eee9dc'], 'Low to bright indirect light', 'Allow soil to dry completely between waterings', false, 'A hardy architectural plant with upright sword-shaped leaves and minimal watering needs.'),
  ('plant', 'ZZ Plant', 'zz-plant', 'Foliage', 48, null, 5, 43, null, array['plants/zz-plant.webp'], 'Easy', array['#292929', '#e9b86d', '#eee9dc'], 'Low to bright indirect light', 'Let the soil dry well between waterings', false, 'A resilient foliage plant with glossy leaflets and an easy-care growth habit.'),
  ('plant', 'Calathea Orbifolia', 'calathea-orbifolia', 'Hanging Plants', 62, null, 4, 31, null, array['plants/calathea-orbifolia.webp'], 'Moderate', array['#292929', '#e9b86d', '#eee9dc'], 'Bright indirect light', 'Keep soil lightly moist and avoid letting it dry completely', true, 'A decorative calathea with broad rounded leaves and distinctive silver-green striping.'),
  ('fertilizer', 'Balanced Growth', 'balanced-growth', 'Bestseller', 18, null, null, 0, null, array['fertilizers/balanced-growth.webp'], null, '{}', null, null, null, 'For foliage and everyday growth.'),
  ('fertilizer', 'Root Revival', 'root-revival', 'Root Care', 22, null, null, 0, null, array['fertilizers/root-revival.webp'], null, '{}', null, null, null, 'For stronger, healthier roots.'),
  ('fertilizer', 'Leaf & Bloom', 'leaf-and-bloom', 'New Formula', 20, null, null, 0, null, array['fertilizers/leaf-bloom.webp'], null, '{}', null, null, null, 'For vibrant foliage and flowers.');
