// Regenerates supabase/setup.sql (every migration in order + seed.sql), the
// single file to paste into the Supabase SQL Editor for a fresh project.
// Run with: npm run build-setup -w server

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const supabaseDir = fileURLToPath(new URL("../supabase", import.meta.url));
const migrations = readdirSync(join(supabaseDir, "migrations"))
  .filter((name) => name.endsWith(".sql"))
  .sort();

const parts = [
  "-- Plantify: complete database setup for a NEW project (schema + products).",
  "-- Paste this whole file into Supabase Dashboard -> SQL Editor -> New query -> Run.",
  "-- Generated by `npm run build-setup -w server`; edit the migrations and",
  "-- seed.sql instead. Existing projects only need the newer migration files.",
  "",
  ...migrations.flatMap((name) => [
    `-- ===== migrations/${name} =====`,
    readFileSync(join(supabaseDir, "migrations", name), "utf8"),
  ]),
  "-- ===== seed.sql =====",
  readFileSync(join(supabaseDir, "seed.sql"), "utf8"),
];

writeFileSync(join(supabaseDir, "setup.sql"), parts.join("\n"));
console.log(`setup.sql written from ${migrations.length} migration(s) + seed.sql`);
